version: '3.8'
services:
  bias_detection:
    build: ./bias-detection
    ports:
      - "5001:5000"
    env_file:
      - common/config/.env
    networks:
      - ai-network

  toxicity_analysis:
    build: ./toxicity-analysis
    ports:
      - "5002:5000"
    env_file:
      - common/config/.env
    networks:
      - ai-network

  reporting:
    build: ./reporting
    ports:
      - "5003:5000"
    env_file:
      - common/config/.env
    networks:
      - ai-network

  api_gateway:
    build: ./api-gateway
    ports:
      - "8080:80"
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge
