apiVersion: apps/v1
kind: Deployment
metadata:
  name: bias-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bias-detection
  template:
    metadata:
      labels:
        app: bias-detection
    spec:
      containers:
      - name: bias-detection
        image: docker.io/library/ethicalaimonitoring-bias_detection:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: bias-detection-service
spec:
  selector:
    app: bias-detection
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5656
  type: ClusterIP
